# Generated by Django 3.2.13 on 2022-04-27 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_router_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='router',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
