# Generated by Django 3.2.13 on 2022-04-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20220428_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(max_length=17),
        ),
    ]
