# Generated by Django 3.2.13 on 2022-04-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('sap_id', models.CharField(max_length=18)),
                ('hostname', models.CharField(max_length=14)),
                ('loopback', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('sap_id', 'hostname', 'loopback', 'mac_address')},
            },
        ),
    ]
