# Generated by Django 3.2.13 on 2022-04-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_router_mac_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='router',
            unique_together={('hostname', 'loopback')},
        ),
    ]
